"use client";

import { motion } from "framer-motion";

const tables = Array.from({ length: 14 }, (_, i) => i + 1);
const speakers = ["L1", "L2", "L3", "R1", "R2", "R3"];

function SpatialPlan() {
  return (
    <div className="relative overflow-hidden rounded-[28px] border border-cream-100/10 bg-[#0b1020] p-4 shadow-2xl md:p-6">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_35%,rgba(95,168,181,.12),transparent_48%),linear-gradient(180deg,#0d1428,#060912)]" />
      <div className="relative min-h-[720px] overflow-hidden rounded-[22px] border border-cream-100/10 bg-[#11182a] p-6">
        <div className="absolute left-[3%] top-[3%] h-[12%] w-[18%] rounded-xl border border-depth-300/40 bg-depth-900/60 p-4 text-[10px] uppercase tracking-[.18em] text-depth-100">Interpretation<br/>Booth</div>
        <div className="absolute left-1/2 top-[3%] h-[12%] w-[28%] -translate-x-1/2 rounded-xl border border-depth-300/40 bg-depth-900/60 p-4 text-center text-[10px] uppercase tracking-[.18em] text-depth-100">Control Unit<div className="mt-4 flex justify-center gap-1">{Array.from({length:5}).map((_,i)=><span key={i} className="h-3 w-8 rounded-sm bg-cream-100/10"/>)}</div></div>
        <div className="absolute right-[3%] top-[3%] font-mono text-[9px] uppercase tracking-[.16em] text-cream-500">Dusit Thani Lakeview · New Cairo</div>

        <div className="absolute left-[6%] right-[6%] top-[19%] bottom-[28%]">
          <div className="grid grid-cols-5 gap-x-5 gap-y-8">
            {tables.map((n) => <div key={n} className="relative flex aspect-square items-center justify-center rounded-full border border-cream-100/20 bg-[#171d2d]">
              <div className="h-[42%] w-[42%] rounded-full border border-signal-500/35 bg-signal-500/10"/>
              <span className="absolute -top-3 text-[7px] font-mono text-cream-500">T{String(n).padStart(2,"0")}</span>
              {Array.from({length:5}).map((_,j)=><span key={j} className="absolute h-3 w-2 rounded-sm bg-cream-100/45" style={{transform:`rotate(${j*72}deg) translateY(-145%)`}}/>) }
            </div>)}
          </div>
        </div>

        <div className="absolute bottom-[19%] left-[19%] right-[19%] flex justify-center gap-1.5">{Array.from({length:10}).map((_,i)=><div key={i} className="h-10 w-8 rounded-t-[14px] border border-signal-400/30 bg-signal-400/10"/>)}</div>
        <div className="absolute bottom-[15%] left-1/2 -translate-x-1/2 font-mono text-[8px] tracking-[.18em] text-signal-400">10 VIP ARMCHAIRS · 2.00 M CLEARANCE</div>

        <div className="absolute bottom-[2.5%] left-[10%] right-[10%] h-[10%] rounded-lg border border-signal-500/40 bg-[#171a26]">
          <div className="absolute inset-x-[10%] top-[18%] h-[55%] rounded border border-signal-400/40 bg-gradient-to-r from-depth-700 via-depth-500 to-depth-700"/>
          <div className="absolute inset-x-0 bottom-[10%] text-center font-mono text-[8px] tracking-[.18em] text-signal-400">STAGE 10 × 3 M · LED 8 × 3 M</div>
        </div>
        <div className="absolute bottom-[11%] left-[27%] h-7 w-10 rounded border border-cream-100/20 bg-cream-100/10"/>
        <div className="absolute bottom-[11%] right-[27%] h-7 w-10 rounded border border-cream-100/20 bg-cream-100/10"/>
        <div className="absolute bottom-[8.5%] left-[21%] text-[7px] uppercase tracking-[.14em] text-cream-500">Monitor L</div>
        <div className="absolute bottom-[8.5%] right-[21%] text-[7px] uppercase tracking-[.14em] text-cream-500">Monitor R</div>

        <div className="absolute left-[5%] top-[24%] bottom-[36%] flex flex-col justify-between">{speakers.slice(0,3).map(s=><span key={s} className="h-12 w-3 rounded-full bg-gradient-to-b from-depth-100/80 to-depth-500/30"/>)}</div>
        <div className="absolute right-[5%] top-[24%] bottom-[36%] flex flex-col justify-between">{speakers.slice(3).map(s=><span key={s} className="h-12 w-3 rounded-full bg-gradient-to-b from-depth-100/80 to-depth-500/30"/>)}</div>
      </div>
      <div className="relative flex flex-wrap gap-x-8 gap-y-2 px-2 pt-4 text-[9px] uppercase tracking-[.16em] text-cream-500"><span><b className="text-depth-300">6 column speakers</b> · 3 left / 3 right</span><span><b className="text-signal-500">2 stage monitor speakers</b></span></div>
    </div>
  );
}

function Section({num,title,kicker,children}:{num:string;title:string;kicker:string;children:React.ReactNode}){
  return <section className="border-t border-cream-100/[.07] px-6 py-24 md:px-12 lg:px-20 xl:px-28"><div className="mx-auto max-w-6xl"><div className="mb-12 flex gap-5"><span className="font-mono text-[10px] tracking-[.2em] text-signal-500">{num}</span><div><h2 className="font-display text-5xl text-cream-50 md:text-6xl">{title}</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-cream-500">{kicker}</p></div></div>{children}</div></section>
}

export default function TNFD(){
 return <main className="min-h-screen bg-[#050813] text-cream-100">
   <aside className="fixed left-0 top-0 z-40 hidden h-screen w-[220px] border-r border-cream-100/[.07] bg-[#050813]/85 px-7 py-8 backdrop-blur-xl xl:block"><div className="text-[9px] uppercase tracking-[.2em] text-cream-500">Paradigm Events</div><div className="mt-2 font-display text-2xl text-cream-50">TNFD<br/>Technical Proposal</div><div className="mt-8 space-y-4 text-[10px] uppercase tracking-[.12em] text-cream-500"><div>01 · Brief</div><div className="text-signal-500">02 · Spatial Concept</div><div>03 · Technical Production</div><div>04 · Interpretation</div><div>05 · VIP Experience</div><div>06 · Guest Experience</div><div>07 · TOR Coverage</div></div><div className="absolute bottom-8 text-[9px] uppercase tracking-[.14em] leading-5 text-cream-500">08 September 2026<br/>Dusit Thani Lakeview<br/>New Cairo · Egypt</div></aside>

   <section className="relative flex min-h-screen items-center overflow-hidden px-6 py-24 xl:pl-[280px] xl:pr-24"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_35%,rgba(46,119,135,.2),transparent_38%),linear-gradient(180deg,#080d1c,#04060d)]"/><div className="relative mx-auto w-full max-w-6xl"><div className="eyebrow text-depth-300">TNFD WORKSHOP · 08 SEPTEMBER 2026</div><motion.h1 initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:1}} className="mt-8 max-w-5xl font-display text-7xl leading-[.92] text-cream-50 md:text-9xl">TNFD<br/><span className="text-depth-100">Workshop</span></motion.h1><p className="mt-8 max-w-2xl font-display text-2xl text-signal-500">Technical & Spatial Proposal</p><p className="mt-8 max-w-xl text-[15px] leading-7 text-cream-300/70">A premium workshop environment designed around clear sightlines, balanced technical coverage, executive comfort and a controlled interpretation workflow.</p><div className="mt-14 grid max-w-3xl grid-cols-2 gap-8 border-t border-cream-100/10 pt-7 md:grid-cols-5"><div><b className="font-display text-3xl text-signal-500">75</b><small className="mt-1 block text-[9px] uppercase tracking-[.15em] text-cream-500">Participants</small></div><div><b className="font-display text-3xl text-signal-500">14</b><small className="mt-1 block text-[9px] uppercase tracking-[.15em] text-cream-500">Round tables</small></div><div><b className="font-display text-3xl text-signal-500">10</b><small className="mt-1 block text-[9px] uppercase tracking-[.15em] text-cream-500">VIP armchairs</small></div><div><b className="font-display text-3xl text-signal-500">6</b><small className="mt-1 block text-[9px] uppercase tracking-[.15em] text-cream-500">Column speakers</small></div><div><b className="font-display text-3xl text-signal-500">1</b><small className="mt-1 block text-[9px] uppercase tracking-[.15em] text-cream-500">Dusit Thani Lakeview</small></div></div></div></section>

   <Section num="01" title="The Brief" kicker="The room is treated as one integrated production environment — not a collection of separate rental items."><div className="grid gap-6 md:grid-cols-3"><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-7"><div className="eyebrow text-depth-300">Venue</div><h3 className="mt-4 font-display text-3xl text-cream-50">Dusit Thani Lakeview</h3><p className="mt-3 text-sm leading-6 text-cream-500">New Cairo, Egypt · private luxury hotel setting.</p></div><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-7"><div className="eyebrow text-depth-300">Format</div><h3 className="mt-4 font-display text-3xl text-cream-50">75 Participants</h3><p className="mt-3 text-sm leading-6 text-cream-500">08:00–18:00 workshop format with executive and technical support.</p></div><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-7"><div className="eyebrow text-depth-300">Presentation</div><h3 className="mt-4 font-display text-3xl text-cream-50">10 × 3 m Stage</h3><p className="mt-3 text-sm leading-6 text-cream-500">8 × 3 m LED screen with podium and presentation support.</p></div></div></Section>

   <Section num="02" title="Spatial Concept" kicker="A balanced 5–4–5 table rhythm, a straight VIP line, rear technical control, isolated interpretation and six evenly distributed column speakers."><SpatialPlan/></Section>

   <Section num="03" title="Technical Production" kicker="The technical layer remains clean and discreet while maintaining reliable coverage throughout the room."><div className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-8"><div className="eyebrow text-signal-500">Audio</div><h3 className="mt-4 font-display text-4xl text-cream-50">6 Column Speakers</h3><p className="mt-4 text-sm leading-7 text-cream-500">Three on the left and three on the right, positioned for balanced room coverage without crowding the stage edge. Two additional monitor speakers face the presenters.</p></div><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-8"><div className="eyebrow text-signal-500">AV / Hybrid</div><h3 className="mt-4 font-display text-4xl text-cream-50">Presentation Ready</h3><p className="mt-4 text-sm leading-7 text-cream-500">6 wireless microphones, 8 × 3 m LED, projector and white screen, Zoom-ready hybrid setup and 90 Mbps dedicated internet.</p></div><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-8"><div className="eyebrow text-signal-500">Stage</div><h3 className="mt-4 font-display text-4xl text-cream-50">10 × 3 m</h3><p className="mt-4 text-sm leading-7 text-cream-500">10 VIP armchairs remain separated from the stage with a minimum 2 m clearance.</p></div><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-8"><div className="eyebrow text-signal-500">Control</div><h3 className="mt-4 font-display text-4xl text-cream-50">Centralized Unit</h3><p className="mt-4 text-sm leading-7 text-cream-500">Rear control position supporting show playback, audio routing, stage monitoring and hybrid coordination.</p></div></div></Section>

   <Section num="04" title="Interpretation" kicker="A dedicated interpretation workflow keeps the language layer isolated while remaining fully connected to the room."><div className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-8"><div className="eyebrow text-depth-300">Interpretation Booth</div><h3 className="mt-4 font-display text-4xl text-cream-50">English ↔ Arabic</h3><p className="mt-4 text-sm leading-7 text-cream-500">Dedicated booth at the rear-left, with simultaneous interpretation and 75 wireless listening headphones.</p></div><div className="rounded-2xl border border-cream-100/10 bg-[#0a1020] p-8"><div className="eyebrow text-depth-300">Control Unit</div><h3 className="mt-4 font-display text-4xl text-cream-50">Central Show Control</h3><p className="mt-4 text-sm leading-7 text-cream-500">Positioned at the rear center to keep the production workflow controlled and visually discreet.</p></div></div></Section>

   <Section num="05" title="VIP Experience" kicker="A dedicated front-row experience gives distinguished guests clear sightlines while preserving the working-table layout behind them."><div className="rounded-[28px] border border-signal-500/25 bg-gradient-to-r from-[#11192b] to-[#0a1020] p-10"><div className="grid gap-8 md:grid-cols-3"><div><div className="font-display text-5xl text-signal-500">10</div><div className="mt-2 text-xs uppercase tracking-[.16em] text-cream-500">Armchairs</div></div><div><div className="font-display text-5xl text-signal-500">2 m</div><div className="mt-2 text-xs uppercase tracking-[.16em] text-cream-500">Clearance from stage</div></div><div><div className="font-display text-5xl text-signal-500">5–4–5</div><div className="mt-2 text-xs uppercase tracking-[.16em] text-cream-500">Table rhythm</div></div></div></div></Section>

   <Section num="06" title="Guest Experience" kicker="The production remains invisible wherever possible. What guests feel is clarity, comfort, sightline and uninterrupted access to the programme."><div className="grid gap-4 md:grid-cols-4"><div className="rounded-xl bg-[#0a1020] p-6 text-sm text-cream-300">Registration & branded materials</div><div className="rounded-xl bg-[#0a1020] p-6 text-sm text-cream-300">Two coffee breaks & buffet lunch</div><div className="rounded-xl bg-[#0a1020] p-6 text-sm text-cream-300">VIP hospitality & reserved seating</div><div className="rounded-xl bg-[#0a1020] p-6 text-sm text-cream-300">On-site technical support</div></div></Section>

   <Section num="07" title="TOR Coverage" kicker="The proposal maps the requested operational requirements into one coordinated event delivery package."><div className="grid gap-3 md:grid-cols-2"><div className="rounded-xl border border-cream-100/10 p-5 text-sm text-cream-300">Venue · Dusit Thani Lakeview, New Cairo</div><div className="rounded-xl border border-cream-100/10 p-5 text-sm text-cream-300">AV · Stage, LED, microphones, projector & hybrid setup</div><div className="rounded-xl border border-cream-100/10 p-5 text-sm text-cream-300">Sound · 6 column speakers + 2 stage monitors</div><div className="rounded-xl border border-cream-100/10 p-5 text-sm text-cream-300">Interpretation · EN ↔ AR + 75 wireless headphones</div><div className="rounded-xl border border-cream-100/10 p-5 text-sm text-cream-300">VIP · 10 armchairs, VIP hospitality and reserved seating</div><div className="rounded-xl border border-cream-100/10 p-5 text-sm text-cream-300">Hospitality · Coffee breaks, lunch and refreshments</div></div></Section>

   <footer className="border-t border-cream-100/10 px-6 py-12 text-center text-[10px] uppercase tracking-[.18em] text-cream-500 xl:pl-[260px]">PARADIGM EVENTS · TNFD WORKSHOP · DUSIT THANI LAKEVIEW · NEW CAIRO</footer>
 </main>
}
